import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'

export default function Third() {
  return (
    <div className={styles.container}>
      <Head>
        <title>First Project</title>
        {/* Change this for create better SEO */}
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className='my-3'>First Project</h1>
    </div>
  )
}
