import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Card, Container, Row, Col } from 'react-bootstrap'


export default function Home() {
  return (
    <Container className='mt-3'>
      <Head>
        <title>Chris Nohall`s Portfolio</title>
        {/* Change this for create better SEO */}
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <h1>
          Welcome to my portfolio!
        </h1>
        <h5>
          Discover projects that display a love for coding and creating great products.
        </h5>
        <div>
          <Col>

          <Row >
          <Link href="/projects" passHref>
            <Card
              role='button'
              bg='light'
              text='dark'
              style={{ width: '20rem' }}
              className="m-3"
            >
              <Card.Body>
                <Card.Title>Projects</Card.Title>
                <Card.Text>
                  {`Some quick example text to build on the card title and make up the bulk
                  of the card's content.`} &rarr;
                </Card.Text>
              </Card.Body>
            </Card>
          </Link>

          <Link href="/gongdo-tech"  passHref>
          <Card
              role='button'
              bg='light'
              text='dark'
              style={{ width: '20rem' }}
              className="m-3"
            >
              <Card.Body>
                <Card.Title>Gongdo Tech</Card.Title>
                <Card.Text>
                {`Some quick example text to build on the card title and make up the bulk
                  of the card's content.`} &rarr;
                </Card.Text>
              </Card.Body>
            </Card>
          </Link>
          </Row>
          <Row>
          <Link href="/about" passHref>
          <Card
              role='button'
              bg='light'
              text='dark'
              style={{ width: '20rem' }}
              className="m-3"
            >
              <Card.Body>
                <Card.Title>About</Card.Title>
                <Card.Text>
                {`Some quick example text to build on the card title and make up the bulk
                  of the card's content.`} &rarr;
                </Card.Text>
              </Card.Body>
            </Card>
          </Link>

          <Link href="/contact" passHref>
          <Card
              role='button'
              bg='light'
              text='dark'
              style={{ width: '20rem' }}
              className="m-3"
            >
              <Card.Body>
                <Card.Title>Contact</Card.Title>
                <Card.Text>
                {`Some quick example text to build on the card title and make up the bulk
                  of the card's content.`} &rarr;
                </Card.Text>
              </Card.Body>
            </Card>
          </Link>
          </Row>
        </Col>
        </div>
    </Container>
  )
}
