import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Chris Nohall`s Portfolio</title>
        {/* Change this for create better SEO */}
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to my portfolio!
        </h1>

        <p className={styles.description}>
          Discover projects that display a love for coding and creating great products.
        </p>

        <div className={styles.grid}>
          <Link href="/projects" passHref>
            <a className={styles.card}>
              <h2>Projects &rarr;</h2>
              <p>Find in-depth information about Next.js features and API.</p>
            </a>
          </Link>

          <Link href="/contact" passHref>
            <a className={styles.card}>
              <h2>Contact &rarr;</h2>
              <p>Learn about Next.js in an interactive course with quizzes!</p>
            </a>
          </Link>

          <Link href="/about" passHref>
            <a className={styles.card}>
              <h2>About &rarr;</h2>
              <p>Discover and deploy boilerplate example Next.js projects.</p>
            </a>
          </Link>

          <Link href="/gongdo-tech"  passHref>
            <a className={styles.card}>
              <h2>Gongdo tech &rarr;</h2>
              <p>
                Instantly deploy your Next.js site to a public URL with Vercel.
              </p>
            </a>
          </Link>
        </div>
      </main>
    </div>
  )
}
